### ISSUE TITLE
dead code?

### ISSUE THREAD

**Issue by jwerle** [yoshuawuyts/nanotick#1]
oops? https://github.com/yoshuawuyts/nanotick/blob/master/index.js#L19-L23

**Comment by yoshuawuyts** [comment]
Haha yeah lines under that should take args not arguments - spotted that on
my way out but guess someone noticed before I could fix it :D - PR welcome
tho!

**Comment by yoshuawuyts** [comment]
ah well fixed; `v1.0.2` :tada: :grin:

**Comment by jwerle** [comment]
nice! 👍 💯
